# ---------------------------------------------------------------------------
# AttriSense — natural_language_sql.py
# ---------------------------------------------------------------------------
# Author : Sharada Dogiparthi <dogiparthi.sharada@gmail.com>
# Version: 1.0.0
# Date   : 2026-05-07
# License: MIT — see LICENSE in repo root.
# Copyright (c) 2026 Sharada Dogiparthi. All rights reserved.
# ---------------------------------------------------------------------------
"""Natural-language to SQL helper for the AttriSense dashboard."""

from __future__ import annotations

import os
import re
import sqlite3
from typing import Any

from dotenv import load_dotenv
from langchain_classic.chains import create_sql_query_chain
from langchain_community.utilities import SQLDatabase
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

from config import DATABASE_PATH, SQL_TABLE_NAME


load_dotenv(override=True)

SQL_PROMPT = PromptTemplate(
    input_variables=["input", "top_k", "table_info"],
    template="""Given an input question, create a syntactically correct SQLite SELECT query.

Rules:
- Use only the table information below.
- Query only the workforce_predictions table.
- Return only SQL. Do not include markdown fences.
- Use SELECT or WITH only. Never write INSERT, UPDATE, DELETE, DROP, ALTER, or PRAGMA.
- If the question is unrelated to the workforce data, return: SELECT 'I do not know' AS answer

Table info:
{table_info}

Question: {input}
SQLQuery:""",
).partial(top_k=10)


def _clean_sql(raw_sql: str) -> str:
    """Normalize SQL text returned by an LLM.

    LLMs sometimes wrap SQL in markdown fences or prepend `SQLQuery:`. The
    database driver needs plain SQL, so this function strips those decorations.
    """
    sql = raw_sql.replace("```sql", "").replace("```", "").strip()
    sql = re.sub(r"^SQLQuery:\s*", "", sql, flags=re.IGNORECASE).strip()
    return sql.rstrip(";")


def _validate_read_only_sql(sql: str) -> None:
    """Block generated SQL that could modify files, schema, or data.

    Args:
        sql: Cleaned SQL string generated by the model.

    Raises:
        ValueError: If the SQL is not a single read-only query.
    """
    normalized = sql.strip().lower()
    if not normalized.startswith(("select", "with")):
        raise ValueError("Only read-only SELECT queries are allowed.")
    if ";" in normalized:
        raise ValueError("Only one SQL statement can be executed at a time.")

    blocked_tokens = ("insert", "update", "delete", "drop", "alter", "pragma", "attach")
    # Regex word boundaries prevent false positives inside harmless words.
    if any(re.search(rf"\b{token}\b", normalized) for token in blocked_tokens):
        raise ValueError("The generated SQL included a blocked operation.")


def _execute_read_only(sql: str) -> dict[str, Any]:
    """Run validated SQL against SQLite and return rows plus column names."""
    with sqlite3.connect(DATABASE_PATH) as conn:
        # SQLite enforces read-only behavior at the connection level too, which
        # gives us a second layer of protection beyond string validation.
        conn.execute("PRAGMA query_only = ON")
        cursor = conn.execute(sql)
        rows = cursor.fetchall()
        columns = [description[0] for description in cursor.description or []]
    return {"columns": columns, "rows": rows}


def query_database_with_ai(user_question: str) -> tuple[str | None, dict[str, Any] | str]:
    """Convert a plain-English HR question into SQL and execute it safely.

    Args:
        user_question: A question such as "How many high risk employees are in
            Manufacturing?"

    Returns:
        A tuple of `(sql_query, result)`. `sql_query` is `None` when the request
        fails, and `result` is either a result dictionary or a user-facing error.
    """
    if not DATABASE_PATH.exists():
        return None, "Database not found. Run `python train_retention_risk_model.py` first."
    if not os.getenv("OPENAI_API_KEY"):
        return None, "OPENAI_API_KEY is not configured. Add it to `.env` to use AI queries."

    db = SQLDatabase.from_uri(f"sqlite:///{DATABASE_PATH}", include_tables=[SQL_TABLE_NAME])
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
    chain = create_sql_query_chain(llm, db, prompt=SQL_PROMPT)

    try:
        # The chain returns SQL text only. We still clean and validate it before
        # running anything because model output should never be trusted blindly.
        raw_sql = chain.invoke({"question": user_question})
        sql = _clean_sql(raw_sql)
        _validate_read_only_sql(sql)
        return sql, _execute_read_only(sql)
    except Exception as exc:
        return None, f"Error: {exc}"


if __name__ == "__main__":
    sql_query, result = query_database_with_ai(
        "How many employees are in the Manufacturing department?"
    )
    print(f"SQL:\n{sql_query}")
    print(f"Result:\n{result}")
