# ---------------------------------------------------------------------------
# AttriSense — natural_language_sql.py
# ---------------------------------------------------------------------------
# Author : Sharada Dogiparthi <dogiparthi.sharada@gmail.com>
# Version: 1.0.0
# Date   : 2026-05-07
# License: MIT — see LICENSE in repo root.
# Copyright (c) 2026 Sharada Dogiparthi. All rights reserved.
# ---------------------------------------------------------------------------
"""Natural-language to SQL helper for the AttriSense dashboard."""

from __future__ import annotations

import os
import re
import sqlite3
from typing import Any

from dotenv import load_dotenv
from langchain_classic.chains import create_sql_query_chain
from langchain_community.utilities import SQLDatabase
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

from config import DATABASE_PATH, SQL_TABLE_NAME


DEFAULT_OPENAI_MODEL = "gpt-4o-mini"

load_dotenv(override=True)

SQL_PROMPT = PromptTemplate(
    input_variables=["input", "top_k", "table_info"],
    template="""Given an input question, create a syntactically correct SQLite SELECT query.

Rules:
- Use only the table information below.
- Query only the workforce_predictions table.
- Return only SQL. Do not include markdown fences.
- Use SELECT or WITH only. Never write INSERT, UPDATE, DELETE, DROP, ALTER, or PRAGMA.
- If the question is unrelated to the workforce data, return: SELECT 'I do not know' AS answer

Table info:
{table_info}

Question: {input}
SQLQuery:""",
).partial(top_k=10)


def _clean_sql(raw_sql: str) -> str:
    """Normalize SQL text returned by an LLM.

    LLMs sometimes wrap SQL in markdown fences or prepend `SQLQuery:`. The
    database driver needs plain SQL, so this function strips those decorations.
    """
    sql = raw_sql.replace("```sql", "").replace("```", "").strip()
    sql = re.sub(r"^SQLQuery:\s*", "", sql, flags=re.IGNORECASE).strip()
    return sql.rstrip(";")


def _validate_read_only_sql(sql: str) -> None:
    """Block generated SQL that could modify files, schema, or data.

    Args:
        sql: Cleaned SQL string generated by the model.

    Raises:
        ValueError: If the SQL is not a single read-only query.
    """
    normalized = sql.strip().lower()
    if not normalized.startswith(("select", "with")):
        raise ValueError("Only read-only SELECT queries are allowed.")
    if ";" in normalized:
        raise ValueError("Only one SQL statement can be executed at a time.")

    blocked_tokens = ("insert", "update", "delete", "drop", "alter", "pragma", "attach")
    # Regex word boundaries prevent false positives inside harmless words.
    if any(re.search(rf"\b{token}\b", normalized) for token in blocked_tokens):
        raise ValueError("The generated SQL included a blocked operation.")


def _execute_read_only(sql: str) -> dict[str, Any]:
    """Run validated SQL against SQLite and return rows plus column names."""
    with sqlite3.connect(DATABASE_PATH) as conn:
        # SQLite enforces read-only behavior at the connection level too, which
        # gives us a second layer of protection beyond string validation.
        conn.execute("PRAGMA query_only = ON")
        cursor = conn.execute(sql)
        rows = cursor.fetchall()
        columns = [description[0] for description in cursor.description or []]
    return {"columns": columns, "rows": rows}


def _openai_key_config_error() -> str | None:
    """Return a user-safe configuration error for missing placeholder keys."""
    load_dotenv(override=True)
    key = os.getenv("OPENAI_API_KEY", "").strip()
    if not key:
        return "OPENAI_API_KEY is not configured. Add a valid key to `.env` to use AI queries."

    placeholder_markers = ("your_openai_api_key", "sk-...", "replace_me", "<")
    if any(marker in key.lower() for marker in placeholder_markers):
        return "OPENAI_API_KEY is still a placeholder. Replace it in `.env` with a valid key."
    return None


def _format_openai_error(error: Exception) -> str:
    """Convert provider errors into safe, actionable app messages."""
    status_code = getattr(error, "status_code", None)
    error_code = getattr(error, "code", None)
    text = str(error).lower()

    if (
        status_code == 401
        or error_code == "invalid_api_key"
        or "invalid_api_key" in text
        or "incorrect api key" in text
    ):
        return (
            "OpenAI authentication failed. The configured OPENAI_API_KEY was "
            "rejected. Add a valid key to `.env` or update the environment, "
            "then try again."
        )
    if status_code == 429 or "insufficient_quota" in text or "rate limit" in text:
        return (
            "OpenAI quota or rate limit blocked the request. Check the account "
            "billing, project limits, or try again later."
        )
    if "model_not_found" in text or "does not exist" in text:
        model_name = os.getenv("OPENAI_MODEL", DEFAULT_OPENAI_MODEL)
        return (
            f"OpenAI model `{model_name}` is unavailable for this key. Set "
            "`OPENAI_MODEL` in `.env` to a model available to the project."
        )
    return f"OpenAI query failed: {error.__class__.__name__}. Check the configured key and model."


def query_database_with_ai(user_question: str) -> tuple[str | None, dict[str, Any] | str]:
    """Convert a plain-English HR question into SQL and execute it safely.

    Args:
        user_question: A question such as "How many high risk employees are in
            Manufacturing?"

    Returns:
        A tuple of `(sql_query, result)`. `sql_query` is `None` when the request
        fails, and `result` is either a result dictionary or a user-facing error.
    """
    smaller_task_hint = (
        "If this question combines multiple asks, break it into smaller tasks "
        "so the AI Assistant can build and verify one safe SQL query at a time."
    )
    if not DATABASE_PATH.exists():
        return None, (
            "Database not found. Run `python train_retention_risk_model.py` first. "
            f"{smaller_task_hint}"
        )
    config_error = _openai_key_config_error()
    if config_error:
        return None, f"{config_error} {smaller_task_hint}"

    db = SQLDatabase.from_uri(f"sqlite:///{DATABASE_PATH}", include_tables=[SQL_TABLE_NAME])
    llm = ChatOpenAI(model=os.getenv("OPENAI_MODEL", DEFAULT_OPENAI_MODEL), temperature=0)
    chain = create_sql_query_chain(llm, db, prompt=SQL_PROMPT)

    try:
        # The chain returns SQL text only. We still clean and validate it before
        # running anything because model output should never be trusted blindly.
        raw_sql = chain.invoke({"question": user_question})
        sql = _clean_sql(raw_sql)
        _validate_read_only_sql(sql)
        return sql, _execute_read_only(sql)
    except ValueError as exc:
        return None, f"SQL validation error: {exc}. {smaller_task_hint}"
    except sqlite3.Error as exc:
        return None, f"SQL execution error: {exc}. {smaller_task_hint}"
    except Exception as exc:
        return None, f"{_format_openai_error(exc)} {smaller_task_hint}"


if __name__ == "__main__":
    sql_query, result = query_database_with_ai(
        "How many employees are in the Manufacturing department?"
    )
    print(f"SQL:\n{sql_query}")
    print(f"Result:\n{result}")
